name: functions-deploy-prd

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.21.0'

      - name: Install Dependencies
        run: go mod download

      - name: Build Project
        run: go build ./...

      - name: Run Unit Tests
        run: go test ./...

      - name: Build File Receiver
        run: GOOS=linux go build -o func
        working-directory: ./cmd/functions/file-receiver