name: functions-deploy-prd

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    environment: production
    env:
        OCI_CLI_USER: ${{ secrets.USER_ID }}
        OCI_CLI_TENANCY: ${{ secrets.TENANT_ID }}
        OCI_CLI_FINGERPRINT: ${{ secrets.AUTH_FINGERPRINT }}
        OCI_CLI_KEY_CONTENT: ${{ secrets.AUTH_KEYFILE }}
        OCI_CLI_REGION: ${{ secrets.REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.21.0'

      - name: Install Dependencies
        run: go mod download

      - name: Build Project
        run: go build ./...

      - name: Run Unit Tests
        run: go test ./...

      - name: Log into OCIR
        uses: oracle-actions/login-ocir@v1.2.1
        id: login-ocir
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}

      - name: Build and push a container image
        id: tag-and-push-image
        run: |
          docker build -f deployments/containers/file-receiver/Dockerfile -t log-analyzer-prd/file-receiver:latest .
          docker push log-analyzer-prd/file-receiver:latest

      - name: Build File Receiver
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: log-analyzer-file-receiver:latest
          context: .
          file: deployments/containers/file-receiver/Dockerfile