name: functions-deploy-prd

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.21.0'

      - name: Install Dependencies
        run: go mod download

      - name: Build Project
        run: go build ./...

      - name: Run Unit Tests
        run: go test ./...

      - name: Build File Receiver
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: log-analyzer-file-receiver:latest
          context: .
          file: deployments/containers/file-receiver/Dockerfile